In [2]:

import numpy as np
import pandas as pd
df = pd.read_csv('USA_Housing.csv', sep=',', header=None)
print(df.values)


[['Avg. Area Income' 'Avg. Area House Age' 'Avg. Area Number of Rooms'
  'Avg. Area Number of Bedrooms' 'Area Population' 'Price']
 ['79545.45857' '5.682861322' '7.009188143' '4.09' '23086.8005'
  '1059033.558']
 ['79248.64245' '6.002899808' '6.730821019' '3.09' '40173.07217'
  '1505890.915']
 ...
 ['63390.68689' '7.250590615' '4.80508098' '2.13' '33266.14549'
  '1030729.583']
 ['68001.33124' '5.534388416' '7.130143864' '5.44' '42625.62016'
  '1198656.872']
 ['65510.5818' '5.992305307' '6.792336104' '4.07' '46501.2838'
  '1298950.48']]


# New section

In [3]:
df_input=df.iloc[:,:-1]
df_input

0                    1                          2  \
0     Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms   
1          79545.45857          5.682861322                7.009188143   
2          79248.64245          6.002899808                6.730821019   
3          61287.06718           5.86588984                 8.51272743   
4          63345.24005          7.188236095                5.586728665   
...                ...                  ...                        ...   
4996       60567.94414          7.830362444                6.137356228   
4997       78491.27543          6.999134987                6.576762661   
4998       63390.68689          7.250590615                 4.80508098   
4999       68001.33124          5.534388416                7.130143864   
5000        65510.5818          5.992305307                6.792336104   

                                 3                4  
0     Avg. Area Number of Bedrooms  Area Population  
1                             4.09       23086.8005  
2                             3.09      40173.07217  
3                             5.13       36882.1594  
4                             3.26      34310.24283  
...                            ...              ...  
4996                          3.46      22837.36103  
4997                          4.02      25616.11549  
4998                          2.13      33266.14549  
4999                          5.44      42625.62016  
5000                          4.07       46501.2838  

[5001 rows x 5 columns]

In [4]:
df_input = df_input.iloc[1: , : ]

In [5]:
from sklearn.preprocessing import Normalizer
norm = Normalizer().fit(df_input)
result_df = norm.transform(df_input)
print('Shape: ',np.shape(result_df))
result_df

Shape:  (5000, 5)


array([[9.60368982e-01, 6.86103750e-05, 8.46233965e-05, 4.93794266e-05,
        2.78731778e-01],
       [8.91943063e-01, 6.75626064e-05, 7.57553559e-05, 3.47779341e-05,
        4.52147720e-01],
       [8.56814211e-01, 8.20071511e-05, 1.19010848e-04, 7.17191588e-05,
        5.15625233e-01],
       ...,
       [8.85478168e-01, 1.01280488e-04, 6.71201798e-05, 2.97530850e-05,
        4.64680965e-01],
       [8.47298744e-01, 6.89586552e-05, 8.88418187e-05, 6.77825726e-05,
        5.31116579e-01],
       [8.15448954e-01, 7.45897680e-05, 8.45482244e-05, 5.06616970e-05,
        5.78828980e-01]])

In [6]:

from sklearn.preprocessing import StandardScaler
result_df = StandardScaler().fit_transform(df_input)
result_df

array([[ 1.02865969, -0.29692705,  0.02127433,  0.08806222, -1.31759867],
       [ 1.00080775,  0.02590164, -0.25550611, -0.72230146,  0.40399945],
       [-0.68462915, -0.11230283,  1.5162435 ,  0.93084045,  0.07240989],
       ...,
       [-0.48723454,  1.28447022, -2.17026949, -1.50025059, -0.29193658],
       [-0.05459152, -0.44669439,  0.14154061,  1.18205319,  0.65111608],
       [-0.28831272,  0.01521477, -0.19434166,  0.07185495,  1.04162464]])

In [7]:
dk=df.iloc[1: ,5:6]
testdata=dk.to_numpy()
testdata.shape

(5000, 1)

In [8]:
arr=np.concatenate((result_df,testdata),axis=1)
print(arr.shape)

(5000, 6)


In [9]:
arrl=arr[0:1000,:]
train_arrl=arr[1001:5000,:]
arr2=arr[1001:2000,:]
templ=arr[0:1000,:]
temp2=arr[2001:5000,:]
train_arr2=np.concatenate((templ,temp2),axis=0)
arr3=arr[2001:3000,:]
temp3=arr[0:2000,:]
temp4=arr[3001:5000,]
train_arr3=np.concatenate((temp3,temp4),axis=0)
arr4=arr[3001:4000,:]
temp5=arr[0:3000,:]
temp6=arr[4001:5000,:]
train_arr4=np.concatenate((temp5,temp6),axis=0)
arr5=arr[4001:5000,:]
train_arr5=arr[0:4000,:]

In [10]:
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(train_arrl[:,:-1], train_arrl[:,-1])

LinearRegression()

In [11]:
print("Intercept: ", mlr.intercept_)
print("Coefficients:")
list(zip(train_arrl[:,:-1], mlr.coef_))

Intercept:  1231858.8866705312
Coefficients:


[(array([-0.17876139217952222, -2.0874223758101147, 0.5053995330346555,
         0.8417004425959769, -1.323203921142252], dtype=object),
  229938.06267454923),
 (array([0.27530503935374767, 1.9451851631686399, 0.7393560419098525,
         0.8417004425959769, 0.410670749283881], dtype=object),
  164070.23780180071),
 (array([-0.23322739623904878, -2.0151427743291745, -0.8312552215465157,
         0.1690985889228559, 0.13139801263712042], dtype=object),
  120898.85315646026),
 (array([0.7356914231917875, 1.598472330297798, 0.6812400521273696,
         1.028084088794553, -1.185056384045706], dtype=object),
  3555.512390696822),
 (array([0.3825726950073012, -0.5341876706962801, -0.8519314610484686,
         0.3311713247477039, 1.2643296418892713], dtype=object),
  151850.84652929194)]

In [12]:
y_pred_mlr= mlr.predict(arrl[:,:-1])
len(arrl[:,:-1])

1000

In [13]:
mlr_diff = pd.DataFrame({'Actual value': arrl[:,-1], 'Predicted value': y_pred_mlr})
mlr_diff.head()

Actual value  Predicted value
0  1059033.558     1.222477e+06
1  1505890.915     1.494121e+06
2  1058987.988     1.253628e+06
3  1260616.807     1.120413e+06
4  630943.4893     8.442622e+05

In [14]:
from sklearn.metrics import r2_score
r2_score(arrl[:,-1], y_pred_mlr)

0.9175886095539684

In [15]:
mlr2 = LinearRegression()
mlr2.fit(train_arr2[:,:-1], train_arr2[:,-1])
print("Intercept: ", mlr2.intercept_)
print("Coefficients:")
list(zip(train_arr2[:,:-1], mlr2.coef_))

Intercept:  1232605.1389198168
Coefficients:


[(array([1.028659694442657, -0.29692704505027545, 0.0212743339309571,
         0.08806222101043115, -1.3175986717917167], dtype=object),
  228340.8412667263),
 (array([1.0008077474755626, 0.025901639828239245, -0.25550610663531237,
         -0.7223014581138117, 0.4039994460165055], dtype=object),
  165246.19772709836),
 (array([-0.6846291548918401, -0.1123028253206403, 1.5162434965413911,
         0.9308404472996439, 0.07240989037045224], dtype=object),
  122539.73968637412),
 (array([-0.491499072791339, 1.221572071386874, -1.3930771719189436,
         -0.5845396326626906, -0.1867342231956508], dtype=object),
  1728.2834178080902),
 (array([-0.8070725337971196, -0.9448336821592221, 0.8467418653292388,
         0.20151313608782562, -0.9883874148428848], dtype=object),
  150031.86566205072)]

In [16]:
y_pred_mlr2= mlr2.predict(arr2[:,:-1])
len(arr2[:,:-1])

999

In [17]:
mlr_diff2 = pd.DataFrame({'Actual value': arr2[:,-1], 'Predicted value': y_pred_mlr2})
print(mlr_diff2.head())
r2_score(arr2[:,-1], y_pred_mlr2)

  Actual value  Predicted value
0  587007.8442     7.117115e+05
1  1734373.044     1.770572e+06
2  762167.2533     7.644995e+05
3  1532845.723     1.572195e+06
4  1243501.651     1.317556e+06


0.9202819078341937

In [18]:
mlr3 = LinearRegression()
mlr3.fit(train_arr3[:,:-1], train_arr3[:,-1])
print("Intercept: ", mlr3.intercept_)
print("Coefficients:")
list(zip(train_arr3[:,:-1], mlr3.coef_))

y_pred_mlr3= mlr3.predict(arr3[:,:-1])

len(arr3[:,:-1])
mlr_diff3 = pd.DataFrame({'Actual value': arr3[:,-1], 'Predicted value': y_pred_mlr3})
print(mlr_diff3.head())
r2_score(arr3[:,-1], y_pred_mlr3)

Intercept:  1231475.1338715567
Coefficients:
  Actual value  Predicted value
0  1375736.957     1.321242e+06
1  636506.0006     7.256343e+05
2  775957.6721     9.326083e+05
3  976540.0985     1.049620e+06
4  1048302.409     1.117822e+06


0.9152808999712615

In [19]:
mlr4 = LinearRegression()
mlr4.fit(train_arr4[:,:-1], train_arr4[:,-1])
print("Intercept: ", mlr4.intercept_)
print("Coefficients:")
list(zip(train_arr4[:,:-1], mlr4.coef_))
y_pred_mlr4= mlr4.predict(arr3[:,:-1])

Intercept:  1231432.7191220946
Coefficients:


In [20]:
mlr_diff4 = pd.DataFrame({'Actual value': arr4[:,-1], 'Predicted value': y_pred_mlr4})
print(mlr_diff4.head())


  Actual value  Predicted value
0  1376240.615     1.317110e+06
1   1680017.24     7.285397e+05
2  1186025.951     9.353049e+05
3  1460044.546     1.047210e+06
4  650939.2067     1.117528e+06


In [21]:
r2_score(arr4[:,-1], y_pred_mlr4)

-0.8507860959810338

In [22]:
mlr5 = LinearRegression()
mlr5.fit(train_arr5[:,:-1], train_arr5[:,-1])
print("Intercept: ", mlr5.intercept_)
print("Coefficients:")
list(zip(train_arr5[:,:-1], mlr5.coef_))


y_pred_mlr5= mlr5.predict(arr3[:,:-1])


len(arr5[:,:-1])
mlr_diff5 = pd.DataFrame({'Actual value': arr5[:,-1], 'Predicted value': y_pred_mlr5})
print(mlr_diff5.head())
r2_score(arr5[:,-1], y_pred_mlr5)

Intercept:  1233028.3853643648
Coefficients:
  Actual value  Predicted value
0  1214689.184     1.320083e+06
1  1672445.348     7.269858e+05
2   1496776.83     9.352679e+05
3  1408427.758     1.051158e+06
4  1447492.964     1.120660e+06


-1.0312641364945883

In [23]:


from mpl_toolkits.mplot3d import Axes3D

In [25]:
def plotChart(iterations, cost_num):
    fig, ax = plt.subplots()
    ax.plot(np.arange(iterations), cost_num, 'r')
    ax.set_xlabel('Iterations')
    ax.set_ylabel('Cost')
    ax.set_title('Error vs Iterations')
    plt.style.use('fivethirtyeight')
    plt.show()


def cost_function(X, y, theta):
    m = y.size
    error = np.dot(X, theta.T) - y
    cost = 1/(2*m) * np.dot(error.T, error)
    return cost, error

In [26]:
def gradient_descent(X, y, theta, alpha, iters):
    cost_array = np.zeros(iters)
    m = y.size
    for i in range(iters):
        cost, error = cost_function(X, y, theta)
        theta = theta - (alpha * (1/m) * np.dot(X.T, error))
        cost_array[i] = cost
    return theta, cost_array

In [28]:
def run():

    data = pd.read_csv('USA_Housing.csv')

    X = data.iloc[1:2801,:-1]
    y = data.iloc[1:2801,-1]

    X = (X - X.mean()) / X.std()

    X = np.c_[np.ones(X.shape[0]), X]

    alpha = 0.01
    iterations = 1000

    theta = np.zeros(X.shape[1])
    initial_cost, _ = cost_function(X, y, theta)
    print('With initial theta values of {0}, cost error is {1}'.format(theta, initial_cost))

    theta, cost_num = gradient_descent(X, y, theta, alpha, iterations)

    plotChart(iterations, cost_num)
    final_cost, _ = cost_function(X, y, theta)
    print('With final theta values of {0}, cost error is {1}'.format(theta, final_cost))
    X1 = data.iloc[2801:,:-1]
    y1 = data.iloc[2801:,-1]
    X1 = (X1 - X1.mean()) / X1.std()

    X1 = np.c_[np.ones(X1.shape[0]), X1]
    print (X1. shape)
    print(y1.shape)
    print(theta.shape)

    print(r2_score(y1, np.dot(X1, theta.T)))

    run()

In [31]:
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration", "num_doors", "body_style", "drive_wheels", "engine_location", "wheel_base", "length", "width",
"height", "curb_weight", "engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg",
 "price"]

In [48]:
df = pd.read_csv("Hitters.csv", header=None, names=headers, na_values="?" )


In [49]:
df.head()

symboling normalized_losses   make fuel_type aspiration num_doors  \
0     AtBat              Hits  HmRun      Runs        RBI     Walks   
1       293                66      1        30         29        14   
2       315                81      7        24         38        39   
3       479               130     18        66         72        76   
4       496               141     20        65         78        37   

  body_style drive_wheels engine_location wheel_base  ... engine_size  \
0      Years       CAtBat           CHits     CHmRun  ...     Assists   
1          1          293              66          1  ...          33   
2         14         3449             835         69  ...          43   
3          3         1624             457         63  ...          82   
4         11         5628            1575        225  ...          11   

  fuel_system    bore     stroke compression_ratio horsepower peak_rpm  \
0      Errors  Salary  NewLeague               NaN        NaN      NaN   
1          20     NaN          A               NaN        NaN      NaN   
2          10     475          N               NaN        NaN      NaN   
3          14     480          A               NaN        NaN      NaN   
4           3     500          N               NaN        NaN      NaN   

  city_mpg highway_mpg price  
0      NaN         NaN   NaN  
1      NaN         NaN   NaN  
2      NaN         NaN   NaN  
3      NaN         NaN   NaN  
4      NaN         NaN   NaN  

[5 rows x 26 columns]

In [50]:
df=df.dropna(subset = ['price'])
df=df.fillna(df.mean())


In [51]:
t = df["num_cylinders"] .value_counts()
t_mask = df["num_doors"].value_counts()
print(t)
print(t_mask)
display(df)

Series([], Name: num_cylinders, dtype: int64)
Series([], Name: num_doors, dtype: int64)


Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 26 columns]

In [52]:
cleanup_nums = {"num_doors":{"four": 4, "two": 2}, "num_cylinders" :{"four": 4, "six": 6, "five":5, "two":2, "three":3, "eight":8, "twelve":12}}


In [53]:
df.replace(cleanup_nums, inplace=True)

In [54]:
df

Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 26 columns]

In [55]:
df=pd.get_dummies(df, columns=['body_style', 'drive_wheels'], prefix=["body", "drive"])

In [56]:
df['fuel_type'] = df['fuel_type'].astype('category')
df.dtypes

symboling              object
normalized_losses      object
make                   object
fuel_type            category
aspiration             object
num_doors              object
engine_location        object
wheel_base             object
length                 object
width                  object
height                 object
curb_weight            object
engine_type            object
num_cylinders          object
engine_size            object
fuel_system            object
bore                   object
stroke                 object
compression_ratio     float64
horsepower            float64
peak_rpm              float64
city_mpg              float64
highway_mpg           float64
price                 float64
dtype: object

In [57]:
df["fuel_type"].value_counts()

Series([], Name: fuel_type, dtype: int64)

In [58]:
df["fuel_type_cat"] = df['fuel_type'].cat.codes

In [59]:
df

Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price, fuel_type_cat]
Index: []

[0 rows x 25 columns]

In [60]:
df['make'] = df['make'].astype('category')
tt_masked=df["make"].value_counts()
print(tt_masked)

Series([], Name: make, dtype: int64)


In [61]:
df["make_cat"] = df['make'].cat.codes
df

Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price, fuel_type_cat, make_cat]
Index: []

[0 rows x 26 columns]

In [63]:
df['aspiration'] = df['aspiration'].astype('category')
tt_masked=df["aspiration"].value_counts()
print(tt_masked)

Series([], Name: aspiration, dtype: int64)


In [64]:
df["aspiration_cat"] = df['aspiration'].cat.codes
df


Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price, fuel_type_cat, make_cat, aspiration_cat]
Index: []

[0 rows x 27 columns]

In [65]:
df['engine_location'] = df['engine_location'].astype('category')
tt_masked=df["engine_location"].value_counts()
print(tt_masked)

Series([], Name: engine_location, dtype: int64)


In [66]:
df["engine_location"] = df['engine_location'].cat.codes
df

Empty DataFrame
Columns: [symboling, normalized_losses, make, fuel_type, aspiration, num_doors, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_cylinders, engine_size, fuel_system, bore, stroke, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price, fuel_type_cat, make_cat, aspiration_cat]
Index: []

[0 rows x 27 columns]

In [67]:
df["fuel_system"] = np.where(df["fuel_system"].str.contains("pfi"), 1, 0)


In [68]:
df["fuel_system"]

Series([], Name: fuel_system, dtype: int64)