In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6])
arr = arr[::-1]   #reversing the array
print(arr)

[6 5 4 3 2 1]


In [17]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 
array2 = array1.flatten()
print(array2)

array3 = np.ravel(array1)
print(array3)


[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
